version: '3.1'

networks:
  newrelic-network:
    driver: bridge

services:
  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    environment:
      - NEW_RELIC_APP_NAME=com.newrelic.monitoring
      - NEW_RELIC_LICENSE_KEY='<%= license_key %>'
      - NEW_RELIC_LOG_LEVEL=info
      - NEW_RELIC_LOG_FILE_NAME=STDOUT
      - NEW_RELIC_ENV=dev
    networks:
      - newrelic-network
    ports:
      - 8080:8080

      